/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Login.Registrado;
import java.util.ArrayList;
import Login.Cliente;
import Login.FacturaEmpresa;

/**
 *
 * @author ok
 */
public class ComprasClientesTotal extends javax.swing.JFrame {

    /**
     * Creates new form ComprasClientesTotal
     */
    public ComprasClientesTotal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        matriz();
    }
   
    Cliente c = new Cliente();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Compras totales de los clientes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "DNI", "Direccion", "Telefono", "Total gastado (S/.)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void matriz(){
        //En esta matriz irá cada cliente que se haya registrado y haya realizado una compra 
        ArrayList<Registrado> r = new ArrayList<Registrado>();
        r = c.rescatarRegistrados();
        String m[][] = new String[r.size()][5];
        //Recorremos a todos los usuarios registrados
        for(int i=0;i<r.size();i++){
            double totalGastado = 0;
            ArrayList<FacturaEmpresa> F = new ArrayList<FacturaEmpresa>();
            F = r.get(i).LanzarFacturas();
            //Con esto estamos dandole al usuario sus facturas por las compras que ha realizado para asi poder cuanto en total ha gastado por todas
            // las compras que ha realizado 
            if(F!=null){
                for(int j=0;j<F.size();j++){
                    double aux3[] = F.get(j).getPrecioUnitario();
                    int aux4[] = F.get(j).getCantidad();
                    totalGastado = totalGastado + aux3[0]*aux4[0];
                }
                m[i][0] = r.get(i).getNombre();
                m[i][1] = String.valueOf(r.get(i).getDNI());
                m[i][2] = r.get(i).getDireccion();
                m[i][3] = String.valueOf(r.get(i).getTelefono());
                m[i][4] = String.valueOf(totalGastado);
            }else{
                
            }
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            m,
            new String [] {
                "Nombre", "DNI", "Direccion", "Telefono", "Total gastado (S/.)"
            }
        ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprasClientesTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprasClientesTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprasClientesTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprasClientesTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprasClientesTotal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
