/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Login.Cliente;
import Login.Empresa;
import Login.HistorialVenta;
import java.util.ArrayList;
import Login.Menu;
/**
 *
 * @author ok
 */
public class GananciasPorEmpresa extends javax.swing.JFrame {

    /**
     * Creates new form GananciasPorEmpresa
     */
    public GananciasPorEmpresa() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        matriz();
    }

    Cliente c = new Cliente();
    Menu m = new Menu();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "RUC", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Total de ganancias (S/.)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Regresar al menú principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ganancias totales de las empresas y sus cantidades vendidas por dispositivo ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(410, 410, 410))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(299, 299, 299))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        InterfazCreador iC = new InterfazCreador();
        iC.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void matriz(){
        //Se mostrara las cantidad total de cada tipo de dispositivos en cada empresa y tambien las ganancias totales 
        ArrayList<HistorialVenta> hV = new ArrayList<HistorialVenta>();
        m.insertarEmpresasInventario();
        ArrayList<Empresa> e = m.getListaE();
        String m[][] = new String[3][8];
        //Recorremos a todos las empresas para saber cuales fueron sus ventas, esto con la ayuda del metodo cliente
        for(int i=0;i<e.size();i++){
           hV = c.rescatarHistorialVenta1(e.get(i));
           int aux1=0,aux2=0,aux3=0,aux4=0,aux5=0;
           double totalGanancias = 0;
           //hacemos esta sentencia if ya que si no se ha realizado ninguna accion de venta por parte de esa empresa todos los valores seran 0 
           if(hV!=null){  
             for(int j=0;j<hV.size();j++){
                 if(hV.get(j).getDispositivo().equals("Placa madre")){
                     aux1 = aux1 + hV.get(j).getCantidadVendida();
                 }
                 if(hV.get(j).getDispositivo().equals("Disco duro ")){
                     aux2 = aux2 + hV.get(j).getCantidadVendida();
                 }
                 if(hV.get(j).getDispositivo().equals("Memoria Ram")){
                     aux3 = aux3 + hV.get(j).getCantidadVendida();
                 }
                 if(hV.get(j).getDispositivo().equals("Procesador")){
                     aux4 = aux4 + hV.get(j).getCantidadVendida();
                 }
                 if(hV.get(j).getDispositivo().equals("Tarjeta de video")){
                     aux5 = aux5 + hV.get(j).getCantidadVendida();;
                 }
                 totalGanancias= totalGanancias + hV.get(j).getTotal();
                 System.out.println("xd");
               }
               m[i][0] = e.get(i).getNombre();
               m[i][1] = e.get(i).getRUC();
               m[i][2] = String.valueOf(aux1);
               m[i][3] = String.valueOf(aux2);
               m[i][4] = String.valueOf(aux3);
               m[i][5] = String.valueOf(aux4);
               m[i][6] = String.valueOf(aux5);
               m[i][7] = String.format("%.2f",totalGanancias);
           }else{
               m[i][0] = e.get(i).getNombre();
               m[i][1] = e.get(i).getRUC();
               m[i][2] = String.valueOf(0);
               m[i][3] = String.valueOf(0);
               m[i][4] = String.valueOf(0);
               m[i][5] = String.valueOf(0);
               m[i][6] = String.valueOf(0);
               m[i][7] = String.valueOf(0);
           }
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            m,
            new String [] {
                "Nombre", "RUC", "Placa madre", "Disco duro", "Memoria Ram", "Procesador", "Tarjeta de video", "Total de ganancias (S/.)"
            }
        ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GananciasPorEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GananciasPorEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GananciasPorEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GananciasPorEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GananciasPorEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
