/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import static GUI.Login.r;
import Login.FacturaEmpresa;
import java.util.ArrayList;
import Login.Cliente;
import Login.Registrado;
import java.util.Iterator;
/**
 *
 * @author ok
 */
public class HistorialCompras extends javax.swing.JFrame {

    /**
     * Creates new form HistorialCompras
     */
    public HistorialCompras() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        matriz();
    }

    Cliente c = new Cliente();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion del dispositivo", "Empresa", "Precio", "Cantidad Comprada", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Historial de compras ");

        jToggleButton1.setText("Regresar al menu principal");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(jToggleButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jToggleButton1)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        InterfazCliente a = new InterfazCliente();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    public void matriz(){
        //Rescatamos a los registrados por que hemos escrito la parte de generar Factura pero sin embargo no lo hemos leido 
        //por lo que la maquina hara q tengamos solo una factura 
        //Recordar cuando nosotros rescatamos al registrado lo que rescatamos tmb es el arraylist de factura compras NO OLVIDARRR
        ArrayList<Registrado> a1 = c.rescatarRegistrados();
        Iterator<Registrado> it = a1.iterator();
        Registrado re=null;
        while(it.hasNext()){
            re = it.next();
            if(re.getUser().equals(r.getUser())&&re.getPass().equals(r.getPass())){
                r = re;
            }
        }
        String m[][] = new String[r.tamañoFactura()][6];
        ArrayList<FacturaEmpresa> a = r.LanzarFacturas();
        for (int i = 0; i < r.tamañoFactura(); i++) {
            int aux[] = a.get(i).getCodigo();
            String aux1[] = a.get(i).getDescripcion();
            String aux2[] = a.get(i).getNombreEmpresa();
            double aux3[] = a.get(i).getPrecioUnitario();
            int aux4[] = a.get(i).getCantidad();
            double total = aux3[0]*aux4[0];
            //descripcion, empresa, precio, cantidadcomprada, total
            m[i][0] = String.valueOf(aux[0]);
            m[i][1] = aux1[0];
            m[i][2] = aux2[0];
            m[i][3] = String.valueOf(aux3[0]);
            m[i][4] = String.valueOf(aux4[0]);
            m[i][5] = String.valueOf(total);  
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            m,
            new String [] {
                "Codigo", "Descripcion del dispositivo", "Empresa", "Precio", "Cantidad Comprada", "Total"
            }
        ));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialCompras().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
