/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import static GUI.Login.a;
import Login.Empresa;
import Login.HistorialVenta;
import Login.Menu;
import Login.Cliente;
import java.util.ArrayList;
import java.util.Iterator;
/**
 *
 * @author ok
 */
public class VisualizarClientes extends javax.swing.JFrame {
 
    Menu m = new Menu();
    Cliente c = new Cliente();
    /**
     * Creates new form VisualizarClientes
     */
    public VisualizarClientes() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        matriz();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "DNI", "Dispositivo", "Codigo de producto", "Precio", "Cantidad comprada", "Total (S/.)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Historial de ventas");

        jToggleButton1.setText("Regresar al menú principal");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jToggleButton1)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jToggleButton1)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        InterfazEmpresa i = new InterfazEmpresa();
        i.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarClientes().setVisible(true);
            }
        });
    }

    public void matriz(){
        //Vamos a recorrer a las empresas para ver a traves de RUC cual es la que el usuario pertenece
        ArrayList<Empresa> e = new ArrayList<Empresa>();
        m.insertarEmpresasInventario();
        e = m.getListaE();
        //Necesitamos m.insertarEmpresasInventario(); ya que a traves de esto estamos ocupando los espacios dentro del arraylist
        //Luego e = m.getListaE(); nos permite botarnos ese arraylist que almacenamos en m.insertarEmpresasInventario();
        Empresa aux =null;
        Empresa aux2 = null;
        Iterator<Empresa> it = e.iterator();
        while(it.hasNext()){
            aux = it.next();
            if(aux.getRUC().equals(a.getRUC())){
                aux2 = aux;
            }
        }
        ArrayList<HistorialVenta> H = new ArrayList<HistorialVenta>();
        H = c.rescatarHistorialVenta1(aux2);
        //Si es nulo es poruqe la empresa no cuenta con clientes por el momento, nadie le compro 
        if(H!=null){
        String m[][] = new String[H.size()][7];
        for (int i = 0; i < H.size(); i++) {
            m[i][0] = H.get(i).getNombre();
            m[i][1] = String.valueOf(H.get(i).getDni());
            m[i][2] = H.get(i).getDispositivo();
            m[i][3] = String.valueOf(H.get(i).getCodigo());
            m[i][4] = String.valueOf(H.get(i).getPrecio());
            m[i][5] = String.valueOf(H.get(i).getCantidadVendida());
            m[i][6] = String.valueOf(H.get(i).getTotal());
          
        }
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            m,
            new String [] {
                "Nombre", "DNI", "Dispositivo", "Codigo de producto", "Precio", "Cantidad comprada", "Total (S/.)"
            }
        ));
        }else{
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
